# pyproject.toml
[project]
name = "cycas"
description = "Cycas is a is a Python solution for post-processing raw forensic artefacts collected with Velociraptor. It optionally ingests data into [Azure Data Explorer (ADX)]"
version = "0.1.0"
requires-python = ">=3.10"
license = "GNU GENERAL PUBLIC LICENSE"
license-files = "LICENSE"

[project.urls]
repository = "https://github.com/nerium-security/cycas"

[tool.setuptools.packages.find]
where = ["."]